# .github/workflows/gitflow-auto-pr.yml
name: GitFlow Auto PR

on:
  push:
    branches:
      - "feature/**"
      - develop
      - "release/**"
      - "hotfix/**"

jobs:
  auto-pr:
    uses: renatofreitasRR/git-flow-module/.github/workflows/gitflow-auto-pr.yml@v1.0.1